# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub
name: Deploy React App to GitHub Pages

# Configura cuándo se debe ejecutar la acción
on:
  # Se ejecuta cada vez que haces un push a la rama "main"
  push:
    branches:
      - main

# Permisos que necesita el workflow para poder escribir en la rama gh-pages
permissions:
  contents: write

# Define los trabajos (jobs) que se van a ejecutar. En este caso, solo uno.
jobs:
  deploy:
    # El tipo de máquina virtual que se usará para ejecutar el trabajo
    runs-on: ubuntu-latest

    # Los pasos que se ejecutarán en orden
    steps:
      # 1. Descarga el código de tu repositorio en la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura el entorno de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Puedes cambiarlo a la versión de Node que uses
          cache: 'npm' # Habilita el caché para las dependencias de npm

      # 3. Instala las dependencias del proyecto
      # Usamos 'npm ci' en lugar de 'npm install' porque es más rápido y seguro para entornos de automatización
      - name: Install dependencies
        run: npm ci

      # 4. Configura el usuario de Git para el commit que hará gh-pages
      # Esto es necesario para que el script gh-pages pueda hacer un commit en tu nombre
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # 5. Ejecuta el comando de despliegue que tienes en tu package.json
      - name: Deploy to GitHub Pages
        run: npm run deploy
